### ISSUE TITLE
If there is no interactivity on a feature, don't change the mouse pointer.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/carto.js#1241]
in embeds like this one https://team.cartodb.com/u/saleiva/editor/b310d3e6-e362-11e4-9987-0e018d66dc29/embed?vector=true it looks like an error (layer with purple circles)

**Comment by alonsogarciapablo** [comment]
This is actually working fine when not using vector tiles: https://team.cartodb.com/u/saleiva/editor/b310d3e6-e362-11e4-9987-0e018d66dc29/embed. So, this is something that needs to be fixed at the d3.cartodb level.
