### ISSUE TITLE
Is there a compressed js file?

### ISSUE THREAD

**Issue by kennynaoh** [CartoDB/carto.js#1257]
Hello @javisantana ,
I am the member of the [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a problem I want to ask.
Is there a `"cartodb.compressed.js"` or a `"cartodb.js"` in [npm](https://www.npmjs.com/package/cartodb.js) package?
Because I just saw a `"cartodb.uncompressed.js"`.
Thanks for your help.

https://github.com/cdnjs/cdnjs/issues/6746
https://github.com/cdnjs/cdnjs/pull/7812

**Comment by karser** [comment]
+1
![image](https://cloud.githubusercontent.com/assets/1675033/16416125/6e593f76-3d49-11e6-9225-40bfd64aa0fb.png)

**Comment by extend1994** [comment]
Hello, any info?

**Comment by sufuf3** [comment]
+1

**Comment by rubenmoya** [comment]
It's available through NPM and through Carto's CDN:

- https://www.npmjs.com/package/@carto/carto.js
- https://cartodb-libs.global.ssl.fastly.net/carto.js/v4.0.9/carto.min.js
