### ISSUE TITLE
Bad infowindows. Layer events fired when layer is disabled.  

### ISSUE THREAD

**Issue by alasarr** [CartoDB/carto.js#1264]
I've created this map: https://geographica.cartodb.com/u/alasarr/viz/b3f5f53e-1908-11e6-8eff-0ea31932ec1d/public_map?redirected=true

This map has two layers with an infowindow:

Municipalities: ign_spanish_adm3_municipalities_displaced_canary
Provinces: ign_spanish_adm2_provinces_displaced_canary

Everything works fine with both layers enabled. However, if I disable provinces layer, feature click doesn't work properly. When I click on municipalities the infowindow is empty. It happens because the layer received at featuredClick event is the provinces layers which is disabled. 

I've not created the event using layer.bind method, I've checked it out directly at cartodb.js (uncompressed version 3.15.8 from bower LINE 39608).

The data is retrieved successfully, but I think, it tries to render the infowindow with the template of the disabled layer. At the code (when click on municipalities with provinces disabled): 

```
    layerView.bind(eventType, function(e, latlng, pos, data, layer) {
        // WRONG: layer IS THE INDEX OF THE DISABLE LAYER
        var infowindowFields = layerView.getInfowindowData(layer);
        if (!infowindowFields) return;
        var fields = _.pluck(infowindowFields.fields, 'name');
        var cartodb_id = data.cartodb_id;

        layerView.fetchAttributes(layer, cartodb_id, fields, function(attributes) {
        // RIGHT: attributes ARE FETCHED SUCCESFULLY. THEY COME FROM THE RIGHT LAYER.

```

I think it could be related with this issue: https://github.com/CartoDB/cartodb.js/issues/1222

**Comment by alonsogarciapablo** [comment]
hola @alasarr! Thanks for reporting this issue and the detailed description of the issue! You're totally right and there's an issue with indexes here... 😞 . It looks like infowindows are not working for layers that have a hidden layer underneath.

**Comment by alonsogarciapablo** [comment]
Might have something to do with [d71da2d0fc39536e83ddd21bb51abc4e1203d620](https://github.com/CartoDB/cartodb.js/commit/d71da2d0fc39536e83ddd21bb51abc4e1203d620).

**Comment by alonsogarciapablo** [comment]
@alasarr it will probably work fine if you make one of the datasets private.

**Comment by alasarr** [comment]
Yes, I know. I forgot to mention before that it worked with namedmaps. Unfortunately, I'm working on something that I need all layers to be public . Today it's not my day... 😥

**Comment by alasarr** [comment]
Right now I can work with all the layers enabled. What I'm doing is setting the opacity to 0 at cartocss.

**Comment by alonsogarciapablo** [comment]
That's a nice workaround! Glad that you were able to make it work with that nice hack. We're currently working hard on the new version of CartoDB.js and we will make sure this bug is fixed there. Thanks!

**Comment by alasarr** [comment]
@alonsogarciapablo great! I'm pretty sure you're doing a really nice work with the new version. I've check out several things that you're doing and looks great, for example d3 and vector tiles :).
