### ISSUE TITLE
CartoDB.js v4 feature requests

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/carto.js#1280]
Capturing here some things that people are asking how to do with CartoDB.js v4 and are not part of the API yet:
- Get layer by ID or table name (@danicarrion)
- Open the infowindow for a layer and a given feature (@danicarrion)
- Access the resulting query for a layer that has source analysis (@AbelVM)
- Get the center of the map (ala `vis.getCenter()`) (@ramiroaznar)
- Get the native map (see https://github.com/CartoDB/cartodb.js/issues/1353) (@AbelVM)

Some other features that have been removed in v4 and we might need to re-implement:
- `force_cors` option to enforce POST request when instantiating maps (it was removed in https://github.com/CartoDB/cartodb.js/pull/1398).

**Comment by ramiroaznar** [comment]
* Be able to modify layer queries.

**Comment by AbelVM** [comment]
* Have access to `L` or `google` objects, not only to the nativemap

**Comment by nygeog** [comment]
* Zoom to extent of selected Widget features
* Query column field in some other place other than in the Category widget.
