### ISSUE TITLE
Example maps not loading due to mixed content

### ISSUE THREAD

**Issue by talos** [CartoDB/carto.js#1293]
The examples linked to here https://github.com/CartoDB/cartodb.js/#examples do not load in Firefox 46.0.1 or Chrome 46.0.2490.71 due to mixed content (JS/CSS linked over HTTP when the main page is served over HTTPS by GitHub).

For example, https://cartodb.github.io/cartodb.js/examples/layer_selector.html loads the JS library as follows:

```
<!-- include cartodb.js library -->
<script src="http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js"></script>
```

And its CSS as follows:

```
<link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/3.15/themes/css/cartodb.css" />
```

This leads to a blank page in Chrome and Firefox.

**Comment by alonsogarciapablo** [comment]
Perhaps we could change it too:

```
<link rel="stylesheet" href="https://libs.cartocdn.com/cartodb.js/v3/3.15/themes/css/cartodb.css" />
...
<!-- include cartodb.js library -->
<script src="https://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js"></script>
```

Notice that I replaced "http://..." by "https://...".

**Comment by talos** [comment]
That wouldn't work, as we host https content at a different URL.  https://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js does not load.

Not sure who to assign this to.

**Comment by matallo** [comment]
haven't thoroughly reviewed the issue, but at quick sight those urls need to be

```<link rel="stylesheet" href="https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/themes/css/cartodb.css" />
<script src="https://cartodb-libs.global.ssl.fastly.net/cartodb.js/v3/3.15/cartodb.js"></script>
```
