### ISSUE TITLE
Popup with header image only (clean the white space below)

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/carto.js#1314]
Clean the white space below
<br>

![image](https://cloud.githubusercontent.com/assets/14546701/16312180/d9c16240-3973-11e6-868e-d6b4b5f5f063.png)

**Comment by piensaenpixel** [comment]
@matallo this happens because if the div is empty we shouldn't show it
![image](https://cloud.githubusercontent.com/assets/1214201/16581330/47502d08-42a9-11e6-872a-dc5e0fad779a.png)

could you take care of it?

**Comment by inigomedina** [comment]
Hey @ivanmalagon, does this issue still make sense?

**Comment by rubenmoya** [comment]
Closing, this was fixed in https://github.com/CartoDB/carto.js/issues/1703#issuecomment-317424968
