### ISSUE TITLE
Investigate root cause of "Maximum number of subsequent equal requests to the Maps API reached (3)" error

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/carto.js#1364]
We're seeing a lot of [these errors in track.js](https://my.trackjs.com/search?query=subsequent). Let's take a look and fix the root cause of this.

cc: @saleiva @xavijam @rochoa

**Comment by alonsogarciapablo** [comment]
Example of one of these errors, related with tooltips: https://my.trackjs.com/details/fc1aa7b446c842a4816e24f987a86e10

**Comment by alonsogarciapablo** [comment]
We're seeing a [lot of errors in track.js with the following message](https://my.trackjs.com/search?query=maximun%20number%20of%20subsequent):

```
["Maximum number of subsequent equal requests to the Maps API reached (3):", {
  "layers": [{
    "id": "c1109752-380f-45d7-a902-0d614dc8619f",
    "type": "cartodb",
    "options": {
      "cartocss": "#layer {\n  polygon-fill: ramp([_2014_score], (#eff3ff, #c6dbef, #9ecae1, #6baed6, #4292c6, #2171b5, #084594), quantiles);\n  line-width: 1;\n  line-color: #050101;\n  line-opacity: 1;\n}",
      "cartocss_version": "2.1.1",
      "interactivity": ["cartodb_id", "country", "_2014_rank", "_2014_score", "fatalities"],
      "source": {
        "id": "a0"
      },
      "attributes": {
        "id": "cartodb_id",
        "columns": ["country", "_2014_rank", "_2014_score", "fatalities"]
      }
    }
  }],
  "dataviews": {},
  "analyses": [{
    "id": "a0",
    "type": "source",
    "params": {
      "query": "SELECT * FROM ashley_data_mapping_terror"
    }
  }]
}, {
  "stat_tag": "26ef9ca8-a774-11e6-86a7-0e3ff518bd15",
  "api_key": "49d8b0717300fd0180338ae382dfcb1f3ae72a55"
}]
```
Error is being triggered by CartoDB.js [here](https://github.com/CartoDB/cartodb.js/blob/846bc76b6160621a7eb7d920ad4c44a3390033c7/src/windshaft/map-base.js#L69).

## About this limitation

In [https://github.com/CartoDB/cartodb.js/pull/1296](https://github.com/CartoDB/cartodb.js/pull/1296) we introduced some changes to limit the number of subsequent "equal" requests to the Maps API. A request to the re-instantiat a map using the Maps API can only be performed if no more than 3 requests with the same payload, params and options, and the same response happened before. When a "new" request is performed, the "request counter" is reset.

The original motivation for this feature, was to prevent infinite loops between cartodb.js and the maps API (eg: when an analysis becomes ready and the map is re-intantiated again, but node is "ready" in the new response -> [https://github.com/CartoDB/cartodb.js/issues/1283](https://github.com/CartoDB/cartodb.js/issues/1283)).


## Error sampling

These are the most common causes of the error:

### Tooltip fields are reset:

[Sample error](https://my.trackjs.com/details/bbc051fba762466dabc2065ea220d61b)

[Code were map is being reloaded](https://github.com/CartoDB/cartodb.js/blob/846bc76b6160621a7eb7d920ad4c44a3390033c7/src/vis/tooltip-manager.js#L29-L31)

### Infowindow fields are reset

[Sample error](https://my.trackjs.com/details/dee8191e8a684185abf06dae472f1d5b)  

[Code were map is being reloaded](https://github.com/CartoDB/cartodb.js/blob/846bc76b6160621a7eb7d920ad4c44a3390033c7/src/vis/infowindow-manager.js#L116-L122)

### New dataview is added

[Sample error](https://my.trackjs.com/details/c776d9a0b41742e98764abe4001f7885)

[Code were map is being reloaded](https://github.com/CartoDB/cartodb.js/blob/846bc76b6160621a7eb7d920ad4c44a3390033c7/src/vis/vis.js#L340-L342)
  
  
I'll open issues for each individual error.

**Comment by saleiva** [comment]
Hi guys, should this fixed? Is happening again in production

**Comment by sonchau** [comment]
I have the same issue, any updates please. Thank you

**Comment by sonchau** [comment]
> I have the same issue, any updates please. Thank you

I have this issue on mr React app, I finally fix by preventing the component update only when cartoCss changes
`  shouldComponentUpdate(nextProps) {
    return nextProps.cartocss !== this.props.cartocss 
    || nextProps.visible !== this.props.visible 
    || nextProps.sql !== this.props.sql;
  }`
