### ISSUE TITLE
Wax.cartodb.js removing popups

### ISSUE THREAD

**Issue by jabrown371** [CartoDB/carto.js#1413]
So, I have a use case where I am building custom named maps on the fly for different users, based on different layers that they have checked. I listen to the interactivity of each layer, and create a custom pop-up based on certain settings. Once I create more than one layer, I was seeing issues where the popup was no longer visible.
If I slow down the process, I can see the popup get created and added to the map. Then, cartodb.js does some clean up, and eventually hits line 2494 of wax.cartodb.js. This function destroys the popup.
Is there anything I can do to stop this from happening? Any reason why it would be occurring?

**Comment by jsanz** [comment]
Are you using a single named map with different layers or instantiating several with `createLayer`?

**Comment by jabrown371** [comment]
I'm actually using both, and both create the same error. I have a large number of datalayers that users can turn on/off, and that is wrapped into 1 layer that contains as many sub-layers as they want to turn on. I also have a layer that is used on startup and almost always left on, I keep that as a separate carto layer... Both are created using the createLayer function.

**Comment by jsanz** [comment]
Have you tried to remove the first layer so you only deal with a single leaflet layer with only one utf-grid and so on. I'm not sure if having two layers (with their own sublayers) would work.

This may be related with #1264, but in that case looks like working with named maps fixed the issue.

cc. @CartoDB/support

**Comment by jabrown371** [comment]
Yes, I've tried with only 1 layer (with multiple sub-layers), or with 2 layers (only 1 sub-layer each). Neither works. Having a single carto layer doesn't seem to help my situation...

**Comment by jsanz** [comment]
Can you provide a minimal working example showing the issue?

--
Jorge Sanz
CARTO - Predict through location

**Comment by jabrown371** [comment]
Ok, so in building the simple example I found our bug: we were listening to the featureOut event, and clearing our tooltip. Apparently this fires on any mouse move where the mouse is not over a feature.
So, to fix the problem, I was going to save the state of the current highlighted data, and only remove it once the corresponding featureOut event fires.
But, featureOut doesn't actually send any data. Your docs and example show it sending a lot of data, or am I confused?
https://carto.com/docs/carto-engine/carto-js/events/#layerfeatureoutlayerindex
Is there any way to know where the featureOut is firing from (what layer), and/or where on the map is it firing (aka lat/lng)?
In my example, the variables passed to the featureOut function are (undefined, 0, undefined, undefined, undefined).
