### ISSUE TITLE
Google map readme example doesnt work

### ISSUE THREAD

**Issue by BHare1985** [CartoDB/carto.js#1557]
The "Load a layer with google maps" on the readme doesnt seem to work anymore.

**Comment by voltagex** [comment]
You need to provide more information with this report, e.g. code samples, error messages, library versions.

**Comment by voltagex** [comment]
Aha. https://cartodb.github.io/cartodb.js/examples/gmaps_force_basemap.html no longer works due to mixed content errors, at least in the latest version of Chrome.

**Comment by karydja** [comment]
I opened a [PR](https://github.com/CartoDB/cartodb.js/pull/1657) to fix this o/
