### ISSUE TITLE
[Google Map Support] Remove "Google Maps" when no API key is present

### ISSUE THREAD

**Issue by noguerol** [CartoDB/carto.js#1577]
Currently, when no Google API key is inserted under user's or organizations profiles the Google Maps option is available under the basemap source selection but when selected a Google error is rendered on the map view. 

![image](https://cloud.githubusercontent.com/assets/70603/22937254/579c176e-f2d8-11e6-8412-5a787203f0fd.png)

As users will probably try to activate them but the visual feedback is not clear enough we should remove Google Maps source option when no API key is present.

**Comment by alonsogarciapablo** [comment]
To clarify... a map might have a Google Maps basemap and it's owner (user/org) might not have a valid API key. We can hide/disable the Google Maps option from the basemap selector, but **the same error message will appear on the map in this case**. This will force them to:

1. enter a valid Google Maps API key.  
2. switch to a non-google-maps basemap.

I guess we could be more clever about this and point users in the right direction. For example, by:
1. Sharing some instructions about how to get and enter the Google Maps API key.
2. Giving them the option to fallback to one of the CARTO basemaps.

This will require a bit of work at BUILDER level tough.

Another option could be to replace the "Oops! Something went wrong" screen from Google, by our own one, and display it whenever we encounter a map with a Google Maps basemap and there's no valid API key.

cc: @xavijam @rochoa @jorgesancha (should we prioritise this or do you guys think it's a nice to have?)

**Comment by rochoa** [comment]
But I think we have two different issues here:
1. If the user does not have an API key (independently of having a valid or invalid one), do not show Google Maps basemaps. This is what @noguerol is asking for, IIRC.
1. If the user has an invalid API key, have a better message for end users, if possible a custom error message that we can fully control. I don't know how feasible that is. BTW, this is an existing problem, just an example: http://srogers.carto.com/viz/81916204-c392-11e3-bcbf-0e230854a1cb/embed_map.

For 1.: I would say yes, we need to not display Google Maps basemaps as an option.
For 2.: I would postpone that as a future improvement.

**Comment by noguerol** [comment]
Following our lets-not-brake-maps rule I would go even further and automatically change, at the time of rendering, for positron whatever map is broken because of a missing or invalid API key. This will fix n2 case. And as you suggest @alonsogarciapablo @rochoa push a warning notification to the user when opening the map in Builder.

If its technically feasible, shall we put the notification thing a as separate ticket?

**Comment by rochoa** [comment]
Feel free to open another issue for case 2. But we need to evaluate other scenarios, like users building applications with cartodb.js, where we might not want to default their maps on the presence of an invalid key.
