### ISSUE TITLE
Pop-ups aren't respecting right margins when the content is too long

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/carto.js#1613]
### Steps to Reproduce

1. Activate pop-ups on a layer
2. Add a column that has long content 
3. Check out the pop-up

### Current Result

![screen shot 2017-03-30 at 18 50 38](https://cloud.githubusercontent.com/assets/16247628/24555341/1a8ffe18-1631-11e7-8656-7fb240f42aeb.png)

### Expected result

To be discussed and defined since this is a bit tricky to solve for every scenario. An ellipsis won't help. Whoever takes this: we should discuss it first between Design and Builder to come up with the best solution.

**Comment by ivanmalagon** [comment]
Not happening anymore.

![image](https://user-images.githubusercontent.com/1078228/39044123-8c8a5c10-448f-11e8-8eae-07f2aa20853f.png)
