### ISSUE TITLE
Method to disable infowindow

### ISSUE THREAD

**Issue by scottsfarley93** [CartoDB/carto.js#1671]
There does not appear to be a method to remove the infowindow created via 
``` cdb.vis.Vis.addInfowindow```.

Specifically, a remove method would be helpful if the infowindow is to be disabled (temporarily) via a user interaction -- details on feature click are not wanted for some period of time. 

As it stands currently, there does not appear to be any way to accomplish this. ```.hide()``` or ```.set('visibility', false)``` only work for a single infowindow instance -- when a feature is clicked again, the window returns.  The template/html for the window can be removed using jQuery, but then the it can not be re-enabled later. If you try to re-create the infowindow after removing the dom element where it is stored, you just get two of them (presumably because the ```overlay``` was not properly removed).

**Comment by knownasilya** [comment]
Could this be opened again?
