### ISSUE TITLE
Files used in a browser

### ISSUE THREAD

**Issue by extend1994** [CartoDB/carto.js#1723]
Hi! I am a member from CDNJS and recently in charge of adding this library. I have a few questions and hope you could help me solve them!
1. On GitHub, I see a lot of files under `dist` folder. However, in README.md (https://github.com/CartoDB/cartodb.js#quick-start) you only mentioned cartodb.css and cartodb.js. Do we only need these two files to use the library on a browser?
2. If we need a uncompressed version for cartodb.js, should we take cartodb.full.uncompressed.js or cartodb.uncompressed.js?
3. There are no `dist` folder (or the folders with packaged files) in many versions/releases, is it possible for you to release them? Or I can only acquire them from cartocdn?

Thanks!

**Comment by rubenmoya** [comment]
It's available through NPM and through Carto's CDN:

- https://www.npmjs.com/package/@carto/carto.js
- https://cartodb-libs.global.ssl.fastly.net/carto.js/v4.0.9/carto.min.js
