### ISSUE TITLE
Improve createVis tests

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/carto.js#1727]
As part of the next carto.js version the `createVis` method is going to be changed.

To ensure this changes wont break anything we decided to add several tests against the generated visModel.

**Comment by rubenmoya** [comment]
Using Jest? :D

**Comment by IagoLast** [comment]
@rubenmoya the original idea was to [compare](https://nodejs.org/api/assert.html#assert_assert_notdeepequal_actual_expected_message) the actual vs expected but since serialising the visModel is not trivial we are going to add regular tests.
