### ISSUE TITLE
Remove support for `sql` option in vizjson layers?

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/carto.js#1754]
Layers in the viz.json used to have a `sql` option before analysis were introduced in BUILDER:

```
{
  "id":"923b7812-2d56-41c6-ac15-3ce430db090f",
  "type":"CartoDB",
  ...
  "options":{
    "sql":"select * from european_countries_e",
    ...
  }
}
```

After analysis were introduced in BUILDER, viz.json v3 is now setting a `source` option with the `id` of an analysis node:

```
{
  "id": "1c9c62bd-1e69-4011-82d3-df0c74c78312",
  "type": "CartoDB",
  ...
  "options": {
    "source": "b0",
    ...
  }
}
```

The question is... can we assume that all layers in viz.json v3 will have the `source` option and remove support for the `sql` option from CartoDB.js?

cc: @juanignaciosl @javitonino @IagoLast

**Comment by juanignaciosl** [comment]
IMHO the actual question is "should the new cartodb.js should support Editor maps"? If the answer is no, you can assume that you have `source` (and remove support for `sql`, as Builder maps have `source`).

**Comment by alonsogarciapablo** [comment]
The thing is that BUILDER is / will also use "the new cartodb.js"... Will CartoDB.js will get any viz.json with the `sql` option in BUILDER?

**Comment by juanignaciosl** [comment]
Not in Builder. Once a map is migrated to Builder, `sql` is replaced with `source`.

_Side note_: I'm saying "the new cartodb.js" because of ignorance. Are we speaking about a new, backwards-incompatible version, or are we dropping support in the current cartodb.js?

**Comment by alonsogarciapablo** [comment]
> Not in Builder. Once a map is migrated to Builder, sql is replaced with source.

Ok, then we'll rely in "source" analyses. 👍 

I'd describe "the new cartodb.js" as the code that BUILDER is using right now with some changes that we're introducing for the first public release of the library. The new public API will be different than the previous version (v3.X).

**Comment by javitonino** [comment]
I have just checked, and we have some Builder maps (which use the embed, with cartodb.js v4) which don't have analyses. I suspect this has to do with the duplicate in builder option of the upgrade visualization dialog. 

Anyway, I agree that cartodb.js v4/vizjson v3 should only rely on source, keep it simple. So I think, we (backend) should review our code to ensure analyses are always added to Builder visualizations, and then run a rake to add analyses for existing Builder visualizations.

**Comment by alonsogarciapablo** [comment]
The error described in https://github.com/CartoDB/cartodb/issues/12881#issuecomment-332859160 is related to what was discussed here. viz.json for some "old" named maps are not including the `source` option in "CartoDB" layers.

**Comment by ivanmalagon** [comment]
Related to Pablo's comment (copypasting from another issue)

New insights about this.

What happens now is that we're making the error noticeable. The maps were already broken but they didn't throw any error.

Setting a previous version of Builder with no `source` checks the map is rendered somehow but broken with no error trace in the browser console.

![image](https://user-images.githubusercontent.com/1078228/31003478-317c86de-a4f0-11e7-8af5-486aefb5e969.png)

For me, we should leave this as it's right now and fix it through backend. If someone complains about this error, Support knows how to answer the customer (republishing the map).

Reverting the check would be overkilling to get non-working maps anyway.
