### ISSUE TITLE
Mock server in the unit tests

### ISSUE THREAD

**Issue by Jesus89** [CartoDB/carto.js#1949]
Currently our v4 suite are performing real requests against the server causing the tests to be slow and fragile.

To avoid this situation we should mock those requests by default while adding a flag to control when to test against real carto servers.

**Comment by IagoLast** [comment]
👍 

What do you think about adding a flag or another suite to use the real server?

Testing only against mocks could lead to integration issues. For example in the `.createVis` tests the real server  request/response were totally different from the one in the tests causing some trouble.

**Comment by ivanmalagon** [comment]
[This section is ignored for the same reasons](https://github.com/CartoDB/carto.js/blob/46c2ea9683508af53fad46cc4e99cc2c9abfb433/test/spec/windshaft/client.spec.js#L188)

Please, unignore the section when fixing this.

**Comment by rubenmoya** [comment]
Leaving this here in case it's interesting for this issue:

https://netflix.github.io/pollyjs
