### ISSUE TITLE
Tooltips not disappearing on public map when using vector rendering

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/carto.js#1953]
**Steps to reproduce:**

1. Import this map to Builder: [test.carto.zip](https://github.com/CartoDB/cartodb.js/files/1548356/test.carto.zip) (you might need to remove the .zip extension first).
2. Make the map public (or private with link) and Publish.
3. Copy the link and open it.
4. Make sure vector is enabled (you can append `vector=true` to the URL).
5. Move your mouse over/out of any of the features.

**Expected result:**

- A tooltip should be displayed when mouse is over one of the green markers.
- Tooltip should disappear when mouse is no longer over a green marker.

**Actual result:**

- A tooltip is displayed when mouse is over one of the green markers.
- Tooltip doesn't disappear when mouse is no longer over a green marker.

![tooltip](https://user-images.githubusercontent.com/390398/33839478-a3e47390-de92-11e7-96db-b757cee199f0.gif)

**Comment by rubenmoya** [comment]
Closing this since we don't support vector in Carto.js anymore
