### ISSUE TITLE
Display "something" when there's a problem with a map

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/carto.js#1991]
Right now, when CARTO.js tries to render a map, and the request to the Maps API fails, map viewers don't get any feedback :(. There's an error in the console, but in terms of the UI, there's just a grey box.

Here's an example of a failing map from El Pais:

![screen shot 2017-12-20 at 18 48 55](https://user-images.githubusercontent.com/390398/34221037-e396de3a-e5b6-11e7-9486-cd0dbdf98809.png)

We could handle this error a bit more gracefully. For instance, we could at least display the basemap and some kind of error on top, or just an error with no map... At least so that viewers know that's supposed to be a map.

cc: @inigomedina @piensaenpixel @ivanmalagon

**Comment by inigomedina** [comment]
Absolutely @alonsogarciapablo.

I don't know well the internal process of building that embed. Maybe it's just a grey box because at that point no information has been fetched yet. If we have a good step-by-step process, it will be easy to go for your approach, and sure we have some kind of solution for that in our design system. If we're doing a more single-one process, it could be difficult to show anything until everything is done.

Could you shed light on this?

**Comment by alonsogarciapablo** [comment]
The way it works right now is... when the embed is loaded, a request to the Maps API is triggered. After that:

1. If the request succeeded, the native Leaflet or Google Maps map is created and map layers are displayed on top.
2. If the request failed (eg: because an analysis timed out, like in the above mentioned case), an error is displayed in the console and that's the end of the story (the native map is not created and no layers are added to it).

**Comment by alonsogarciapablo** [comment]
Here's how this looks in the context of Builder:

![screen shot 2017-12-28 at 12 54 27](https://user-images.githubusercontent.com/390398/34410119-4ada41f0-ebce-11e7-8d76-b1345376358a.png)

In this case, for example I tried to geocode a dataset and it failed.

**Comment by piensaenpixel** [comment]
Ok, open a ticket in design repo to think about it.

**Comment by piensaenpixel** [comment]
@alonsogarciapablo can we have more information about the errors or only that 'something' happened?

**Comment by alonsogarciapablo** [comment]
Yes, we get some error information from the backend in CARTO.js. I think right now we display this error message in the "alert" on the lower left hand side (see image above).

**Comment by arianaescobar** [comment]
The proposed solution for this issue can be found [here](https://github.com/CartoDB/design/issues/1152#issuecomment-392722389). It should be ready for prioritization and implementation.

**Comment by alonsogarciapablo** [comment]
Thanks @arianaescobar!
