### ISSUE TITLE
Use torque only as renderer

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#1999]
Currently, carto.js and torque both instantiate the map when there's a change in a torque layer.

That provokes race condition errors. For instance, we have a support issue with Torque not showing the proper filtered values -> https://github.com/CartoDB/support/issues/1038 Depending on who instantiate the map last (cartodb.js or torque) the result is the right one or not.

@rochoa told me to use torque only as renderer and let carto.js the instantiation task. I need to talk to him to ellaborate this because I don't remember the exact details.

The outcomes of doing this are two:

- Potentially fix the issue linked above (and similar problems).
- Proof that carto.js can use other renderers. This will pave the path to incorporate vector tile renderers. \o/

**Comment by ramiroaznar** [comment]
How is this issue going?

**Comment by Jesus89** [comment]
Hi. I found a fix for the issue (https://github.com/CartoDB/cartodb/pull/14156).

Since the issue is solved I think we could close this one because it won't use other renderers since vector rendering is addressed in CARTO VL.

**Comment by ramiroaznar** [comment]
@ivanmalagon what do you think?

**Comment by ivanmalagon** [comment]
Totally agree.

Superb work @Jesus89 (as usual)

**Comment by Jesus89** [comment]
:blush:
