### ISSUE TITLE
Split legends data and visualization

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2018]
### Context

There's an [ongoing revamp on Builder](https://github.com/CartoDB/cartodb-management/issues/5082) to provide responsive legends. You can see the Invision project in that ticket.

The problem is that the legends rendering takes place in `carto.js`, so Builder has no control about where or how to draw legends.

We have to provide legends as we do with dataviews: provide the needed data to render them from `carto.js` but leave the UI stuff to the host (Builder in this case).

Tasks:
- Provide all the needed info to render legends from `carto.js`. Research about this because it's likely we're doing it already.
- Move UI work to Builder (Deep Insights in Builder): code and styles.

All this work is for the internal `carto.js` API, not the public one.

**Comment by Jesus89** [comment]
Now in the public API we have nice metadata objects. May be we can use this approach...

**Comment by ivanmalagon** [comment]
First of all, do we expose the legends metadata or it's the user the responsible for building a legends from the current metadata we expose (buckets and categories) ?

Apart from that, it's not possible to use at the same time the public API and the internal one instantiated by `createDashboard`. Perhaps, we can access the internal metadata via client but I'm not sure. Any thoughts?
