### ISSUE TITLE
Adapt carto.js to Google Maps v3.32 / v3.31

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2067]
On February 13th, 2018 Google released a new experimental version of Google Maps (v3.32) that doesn't get along with CARTO.js.

The problems seem related to some race condition or us doing things before the script is ready. That was not happening with previous versions.

We are now operating on the frozen version (v3.30) and still have the cushion of v3.31, but we should tackle this. Google Maps bumps version every 3 - 4 months so that's the time we have

**Comment by knownasilya** [comment]
The biggest issue is that the layers from Carto don't show on initial load, but do show up once you start zooming. I'd love to get this working, especially since `3.32` contains the new beta renderer which is 👌

**Comment by VictorVelarde** [comment]
Hi @knownasilya 

We have been testing gmaps *3.32* and it seems that there are no more issues by now (v3.32.12). 

But this version is still experimental, so we have decided to allow just the currently `stable`version **v3.31** and to wait for next release. This has been included in our new carto.js v4.0.1, available at NPM. 

We have also updated our development docs at https://carto.com/developers/carto-js/ (see for example this [gmaps map](https://carto.com/developers/carto-js/examples/#example-add-a-layer-gmaps))

As a reference: [Google Maps releases](https://developers.google.com/maps/documentation/javascript/releases)

**Comment by ivanmalagon** [comment]
Reopening. -> https://github.com/CartoDB/support/issues/1568

**Comment by ivanmalagon** [comment]
After spending the whole day trying to know what the issue is with cartodb.js v3, I ended up filing an issue to Google Maps team.

https://issuetracker.google.com/issues/80553979

I couldn't make any fix for that and I hope to get an answer for them. So far, there's nothing more we can do but I'll be on top of this, since it can break our library with GMaps. Depending on the answer, perhaps we need to rethink / refactor how we render CARTO.js with GMaps. 😨 

Regarding JLL we need more info. Are they suffering from the very same issue or are they getting another error? We need that feedback to tackle it correctly in v4.

**Comment by ivanmalagon** [comment]
Fixed for cartodb.js v3 at v3.15.15

To get the last version -> [http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js](http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js)

**Comment by ivanmalagon** [comment]
Closing.

The JLL problem is not related to GMaps 3.32. It has now its own ticket. https://github.com/CartoDB/carto.js/issues/2132
