### ISSUE TITLE
Fix cartodb.js v3 live examples

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2095]
With the renaming of the repo, previous GitHub pages stopped working
https://carto.com/docs/carto-engine/carto-js/getting-started/#cartojs-usage-examples

The link was `http://cartodb.github.io/cartodb.js/examples/easy.html`
and now it's `http://cartodb.github.io/carto.js/examples/v3/easy.html`

**Comment by IagoLast** [comment]
Fixed in https://github.com/CartoDB/carto.js/commit/c20facdc912ca73986e37a28e0296a73c3353297
