### ISSUE TITLE
Create layer from vizjson URL

### ISSUE THREAD

**Issue by karydja** [CartoDB/carto.js#2099]
In the [previous version](https://carto.com/docs/carto-engine/carto-js/api-methods/#cartodbcreatelayermap-layersource--options--callback) of carto.js, we were able to create a layer providing a vizjson URL of an existing map in our accounts. This way, the `cartoCSS` style already defined in the map was used in the layer. Is this possible in carto.js v4?

**Comment by alonsogarciapablo** [comment]
cc: @inigomedina
