### ISSUE TITLE
featureOverColumns brings all date fields back as null

### ISSUE THREAD

**Issue by gingemonster** [CartoDB/carto.js#2101]
CartoJS 4 latest version

If you use the featureOverColumns option and give it a field name that is a date column in carto then the data that comes back from the carto API in the grid.json file has null values for anything that is a date.

If I tweak my source.SQL to select a date field as a string like this "to_char(start_date, 'YYYY-MM-DD') as start_date" then it comes back with the correct data.

**Comment by ivanmalagon** [comment]
This issue won't be fixed at Windshaft level (https://github.com/CartoDB/Windshaft-cartodb/issues/946)[https://github.com/CartoDB/Windshaft-cartodb/issues/946#issuecomment-385003198] so the workaround pointed by @gingemonster it's the way to go.

**Comment by gingemonster** [comment]
is something going to be added to the documentation to reflect this, otherwise support are likely to get asked this repeatedly

**Comment by ivanmalagon** [comment]
You're right. Added this issue https://github.com/CartoDB/carto.js/issues/2174 to tackle it.
