### ISSUE TITLE
Refactor examples to use default_public

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2110]
### Context

AUTH API is about to remove the feature of falling back to `default_public` in case the user provides a non existent key.

We need to refactor all CARTO.js examples to use `default_public` instead of what it's used now, `YOUR_API_KEY`

Sync with @enekid

**Comment by ivanmalagon** [comment]
Summoning @csubira 

Did you tell me that you did this already / working on it?

**Comment by enekid** [comment]
It's already in production:

https://carto.com/developers/carto-js/examples/
