### ISSUE TITLE
Angular 5 Example

### ISSUE THREAD

**Issue by dersteppenwolf** [CartoDB/carto.js#2114]
Could you include an example integrating Angular 5 and CARTO.js v4?

Thanks

**Comment by ivanmalagon** [comment]
Hi Juan Carlos.

One of our teammates has a repo with a working example on [https://github.com/jesusbotella/cartojs-angular-example](https://github.com/jesusbotella/cartojs-angular-example)

Hope it helps. Don't hesitate to ask for help or clarifications if needed.
