### ISSUE TITLE
Remove dataview method does not stop fetching data from dataChanged event

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/carto.js#2119]
### Context

The [remove dataview event](https://carto.com/developers/carto-js/reference/#cartoclientremovedataview), removes the dataview from the client element, but it does not stop fetching data when there is the `dataChanged` event.

You need to use the [disable() method](https://carto.com/developers/carto-js/reference/#cartodataviewbasedisable) to stop fetching data from the dataview after remove it from the client.

This leads to confusion when using these methods on CARTO.js to deal with dataviews.

### Steps to Reproduce

1. Create a map with one dataview that contains the dataChanged event
2. Apply the removeDataview method, the dataview is removed from the client, but it still keeps fetching data when you move around the map or change the zoom level.
3. If you add the disable() method, then the dataview stops being updated when the map position or zoom changes.

### Expected result

The dataview should stop being updated once it is removed from the client using the removeDataview() method.

There should be no need to add the disable() method after applying the removeDataview() method.

I'm adding an HTML example with this issue:

[test_rm_dataview.html.zip](https://github.com/CartoDB/carto.js/files/2012303/test_rm_dataview.html.zip)

cc @Jesus89

**Comment by Jesus89** [comment]
Thanks for the feedback!

This should be an easy one. Just adding `dataview.disable()` to the `client.removeDataview()` function: https://github.com/CartoDB/carto.js/blob/1c362ce72593464ba738811a9a74072bcfa655d9/src/api/v4/client.js#L295

**Comment by rubenmoya** [comment]
Fixed in version `4.0.14`
