### ISSUE TITLE
Add options as input argument to the getLeafletLayer() method

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/carto.js#2125]
### Context

According to the documentation, the methods getleafletLayer() , returns a leaflet layer that groups all the layers that have been added to this client, it returns a [L.TileLayer](https://leafletjs.com/reference-1.3.0.html#tilelayer) layer that groups all the layers.

However, if you want to add or change the options of the layer, it is not possible using the methods of Leaflet and CARTO getLeafletLayer() method does not accepts input arguments to change the options of the Layer generated.

It would be nice to have this option in CARTO.js. 

For example, at this moment we can add the option noWrap to the L.tileLayer of the basemap but not for CARTO layer. Therefore the result is the next one:

![screen shot 2018-05-25 at 11 20 38](https://user-images.githubusercontent.com/11177693/40536885-c7b56548-600d-11e8-8bd4-502c25ab157f.png)

**Comment by Jesus89** [comment]
Hi @oriolbx.

This is a really good point in order to enable better integration with native Leaflet Layers.

This is also easy to implement:
- Add an `options` parameter to the `getLeafletLayer()` function
- Merge these options with our defaults
- Apply the merged options to the internal L.tileLayer instance

Thanks :+1:

**Comment by rubenmoya** [comment]
I've opened a PR to solve this, although your example won't work if you only use `noWrap`, you can read more about it [here](https://stackoverflow.com/a/47482145). Using this options works:

```
{
  noWrap: true,
  bounds: [
    [-90, -180],
    [90, 180]
  ]
}
```

**Comment by rubenmoya** [comment]
Fixed in `@carto/carto.js@4.0.9`
