### ISSUE TITLE
Layers not added in GMaps wheen using multiple clients

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2132]
### Context
A customer reported that their layers where not showing up.

After some triage, the problem is that internally we don't handle well the layers added to Google Maps when using layers from multiple clients.

This is a tricky issue since it affects the CARTO.js internals so we must proceed carefully.

Another insight from the ticket is that calling to `getGoogleMapsMapType` already adds it to Google Maps but then we are pushing the layer to the `overlayMapTypes` array, so it's twice in GMaps. Take a look on it too.

You can find a working HTML in [support](https://github.com/CartoDB/support/issues/1568#issuecomment-395365534)

Check in Leaflet as well.

**WARNING**
Be careful with this issue. Builder is working flawlessly since it only needs one client. Test it thoroughly or set a flag only in the public API to allow several clients.

**Comment by rubenmoya** [comment]
Fixed in version `4.0.15`
