### ISSUE TITLE
Can't hide cartodb layer on gmap 3.32

### ISSUE THREAD

**Issue by cantacell** [CartoDB/carto.js#2138]
### Context
Google Maps v3.32
cartobjs v.3.15.16

### Steps to Reproduce
1. After loading and clicking on 'hide cartodb' button nothing happens;
2. If click on zoom in or zoom out then the layer will be hidden

http://jsfiddle.net/b5f0gszt/1/

### Browser and version

Chrome 66, Firefox 60, Opera 53
Windows 7

**Comment by ivanmalagon** [comment]
cartodb.js updated to v3.15.17

The fiddle now it's working properly, hiding and showing layers.
