### ISSUE TITLE
Add metrics to CARTO.js v4

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2139]
Right now we don't have any clue of how much CARTO.js v4 is being used. We need to add metrics to get a sense of the library usage.

Apparently, MAPS API accepts a flag / parameter / attribute in the maps instantiation for this purpose. Ask someone in Engine for info about this and add the code necessary.

**Remarks**
Add it only when the map gets instantiated using the public API.

**Comment by rubenmoya** [comment]
Fixed in version `4.0.13`
