### ISSUE TITLE
Debounce map instantiation

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2140]
### Context
Our users are hitting platform limits when doing some changes programatically, like `setOperation` in 6 different dataviews at the same time. This triggers six different map instantiations and Windshaft complains about it.

We need to implement some light debouncing to fix this and to avoid breaking the existing API or introducing new concepts.

There's an ongoing PR about this started by @Jesus89 [https://github.com/CartoDB/carto.js/pull/2087](https://github.com/CartoDB/carto.js/pull/2087)

**NOTE:** we need to be careful with this changes regarding this library and Builder.

**Comment by rubenmoya** [comment]
Fixed in version `4.0.12`
