### ISSUE TITLE
Histogram basic changes

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2142]
### Context
Right now, in CARTO.js v4.0 the only parameter available is `bins` to set the desired number of bins. There are cases where it'd be great to allow the user to control the range of the histogram: to get a more detailed histogram, for instance.
Internally, we already have a `start` and `end` parameters. We can expose them in the public API.

### Tasks
- Expose `start` and `end` parameters.
- Specs.
- Add documentation.
- Modify examples.

**Comment by rubenmoya** [comment]
Added in version `4.0.18`
