### ISSUE TITLE
Changes from v3.15 to v4

### ISSUE THREAD

**Issue by juanfkt93** [CartoDB/carto.js#2149]
Hi, I have a doubt regarding adding a Torque Layer.

With CartoDB 3.15, I can add a Torque Layer the following way:

       var layerSource = {
          type: "torque",
          options: {
              ......
          }
        }

        **cartodb.createLayer**(map, layerSource).done(function(layer) {
          map.addLayer(layer);
        });

Can I do something of the sort in Cartojs, v4? The new **carto.layer.Layer** doesn't seem to work for me.

Thanks

**Comment by ivanmalagon** [comment]
I'm sorry but torque is not supported yet in CARTO.js v4.

**Comment by juanfkt93** [comment]
Oh okay, thanks for the reply!
