### ISSUE TITLE
Aggregation on date results in uncaught error

### ISSUE THREAD

**Issue by sverhoeven** [CartoDB/carto.js#2161]
### Context

While testing https://github.com/sverhoeven/docker-cartodb there is a mismatch between the date aggregations in https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/models/dataview/histograms/date-histogram.js#L131-L132 and https://github.com/CartoDB/carto.js/blob/master/src/dataviews/helpers/histogram-helper.js#L3-L13

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create map with Storm Events 2014
2. Choose animation as aggregation
3. Select created_at as column

### Current Result

The plot below the map stays grayed out/loading and the DevTools console I got the following error:
```js
Uncaught Error: aggregation "millennium" is not defined
    at Object.helper.add (histogram-helper.js:87)
    at Object.helper.fillTimestampBuckets (histogram-helper.js:41)
    at child.parse (histogram-dataview-model.js:169)
```

### Expected result

The plot below the map to be drawn with data from the created_at column.

### Browser and version

Google Chrome 67

### Additional info
The Docker image was build with release v4.12.30 of https://github.com/CartoDB/cartodb

**Comment by rubenmoya** [comment]
Hi Stefan, we've released a new version (4.0.10) with those changes, you can check out the new values in [the documentation](https://carto.com/developers/carto-js/reference/#cartodataviewtimeaggregation).

Thank you for your contribution!
