### ISSUE TITLE
Doc note about interactivity with date fields.

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2174]
### Context

When setting interactivity on date columns, the grid.json doesn't return any value. It's a [known bug](https://github.com/CartoDB/Windshaft-cartodb/issues/946#issuecomment-385003198%5D) and won't be fixed.

The workaround at CARTO.js level is to modify the SQL sentence to cast the data as in

```
"to_char(start_date, 'YYYY-MM-DD') as start_date" 
```

### Task
Reflect all this on the reference to aware the developers about this on advance.

**Comment by Baschdl** [comment]
@ivanmalagon Could you please document this? That's a pretty confusing behavior
