### ISSUE TITLE
Fix guides

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto.js#2182]
### Context
We were checking the docs before and after releasing a new carto.js version (4.1.2) and we saw some errors to be fixed.

### Issues
1. Code in https://carto.com/developers/carto-js/reference >> `Loading the library` section doesn't correspond to __latest__ and it doesn't show either __current__ version (nor it did before releasing), it looks hardcoded.
- **a. Wrong code**
```html
<!-- CDN: load the latest CARTO.js version -->
<script src="https://libs.cartocdn.com/carto.js/v4.0.8/carto.min.js"></script>
<!-- CDN: load a specific CARTO.js version--> <script src="https://libs.cartocdn.com/carto.js/%VERSION%/carto.min.js"></script>
```
- **b. Correct code** 
```html
<!-- CDN: load the latest CARTO.js version -->
<script src="https://libs.cartocdn.com/carto.js/v4/carto.min.js"></script>
<!-- CDN: load a specific CARTO.js version-->
<script src="https://libs.cartocdn.com/carto.js/%VERSION%/carto.min.js"></script>
```
As pointed by @Jesus89 this should be in the CartoDB/developer scripts >>
Missing `cartojs-reference` task here: https://github.com/CartoDB/developers/blob/f08932a58161eabef7a9dbfbca663f074117e20b/Gruntfile.js#L207

2. We should also get rid of 4.0 references (--> 4)

**Comment by Jesus89** [comment]
I found also the following issues:

### guides/01-overview.md

```js
<script src="https://libs.cartocdn.com/carto.js/v4.0.8/carto.min.js"></script>
```
Change to

```js
<script src="https://libs.cartocdn.com/carto.js/%VERSION%/carto.min.js"></script>
```

### guides/05-upgrade-considerations.md

`version 4.0 of CARTO.js` to `version 4 of CARTO.js`

### reference/01-introduction.md

`CARTO.js 4.0` to `CARTO.js v4`

### reference/02-authentication.md

`CARTO.js 4.0` to `CARTO.js v4`

### support/02-faq.md

`CARTO.js 4.0` to `CARTO.js v4`

### support/05-release-announcement.md

`CARTO.js 4.0` to `CARTO.js v4`

**Comment by Jesus89** [comment]
Regarding missing `cartojs-reference`: https://github.com/CartoDB/developers/pull/390

**Comment by VictorVelarde** [comment]
Version selector seems also "hardcoded" somehow.

Being v4.1.2 our current last version we see v4.1.1 ...

![image](https://user-images.githubusercontent.com/458196/43633929-08c194ba-970b-11e8-93dd-e5f69345ebb0.png)
