### ISSUE TITLE
Removing a layer causes a redraw of the map (Cartodb 4)

### ISSUE THREAD

**Issue by cantacell** [CartoDB/carto.js#2185]
Removing a layer causes a full redraw of the map;
jsfiddle at http://jsfiddle.net/to2fjnd7/6/

Tested on Cartodb 4.1.3 and Leaflet 1.3.3.

**Comment by jesusbotella** [comment]
Hello @cantacell!

I reviewed the fiddle you link and seems like the behaviour is correct according to the code.
Whenever you remove a layer from the map, we need to request the new tiles and redraw the map accordingly to the layer stack.

Feel free to ask anything else. :)
