### ISSUE TITLE
Fix the position of tooltip exactly on the center of marker and not move with mouse cursor

### ISSUE THREAD

**Issue by AryaRDI** [CartoDB/carto.js#2196]
I am trying to add a tooltip for my markers on the map and so far so good, no problem to make it work. the problem happens when I want to mask the tooltip exactly on the point which it moves with the mouse cursor.

Here is an example of a tooltip which works fine and moves with mouse cursor when the hover happens.
http://bl.ocks.org/oriolbx/688c63b865e7045e9f90

I expected an option, etc to let me fix the tooltip on a position beside the marker while it is on hover and prevent it to move with the mouse cursor.

I hope somebody has a solution for that or CartoDB guys just come up with an update to give the user an option to fix the position of the tooltip with the center of the marker, not with the mouse cursor position.

Thanks

**Comment by ivanmalagon** [comment]
Hello.

The `featureOver` event is triggered along all the movement on top of a feature. It has two properties that can be useful in your case: `data.cartodb_id` and `position`.

````
layer.on('featureOver', event => {
  console.log(event.data.cartodb_id, event.position);
});
````

I don't get exactly what your problem is but I think you have several scenarios:

- If you want the tooltip to follow the mouse movement, you just need to update its position according to the one returned by the event.

- If you want the tooltip to stay in the first position, just remember its `cartodb_id` and don't update the tooltip position if it's the same as the latest.

- If you need the position of the marker in some other place of the polygon, the event only returns its position relative to the mouse movement. You'd to get the `cartodb_id` of the feature and ask via SQL API and some PostGIS query to get the center of the geometry, if that's what you need.

Hope this helps.

**Comment by AryaRDI** [comment]
> Hello.
> 
> The `featureOver` event is triggered along all the movement on top of a feature. It has two properties that can be useful in your case: `data.cartodb_id` and `position`.
> 
> ```
> layer.on('featureOver', event => {
>   console.log(event.data.cartodb_id, event.position);
> });
> ```
> I don't get exactly what your problem is but I think you have several scenarios:
> 
> * If you want the tooltip to follow the mouse movement, you just need to update its position according to the one returned by the event.
> * If you want the tooltip to stay in the first position, just remember its `cartodb_id` and don't update the tooltip position if it's the same as the latest.
> * If you need the position of the marker in some other place of the polygon, the event only returns its position relative to the mouse movement. You'd to get the `cartodb_id` of the feature and ask via SQL API and some PostGIS query to get the center of the geometry, if that's what you need.
> 
> Hope this helps.

Hi Ivan,

The last scenario is exactly what I am looking for, can you refer me to the document about this? or an example to get the marker position by SQL API and PostGIS? that will be very helpful. FYI I'm using v3.15.14 Cartodb


Thanks

**Comment by IagoLast** [comment]
Hi @AryaRDI!

Can you provide an example of your failing code and specify the CARTO.js version that you are using?

Regards,

**Comment by IagoLast** [comment]
@AryaRDI wops, dint read, sorry :( 

can you provide your failing code?

**Comment by AryaRDI** [comment]
> Hi @AryaRDI!
> 
> Can you provide an example of your failing code and specify the CARTO.js version that you are using?
> 
> Regards,

Hi @IagoLast,

I already mentioned that too. I used the same approach as here:

http://bl.ocks.org/oriolbx/688c63b865e7045e9f90

**Comment by IagoLast** [comment]
@AryaRDI Im not a carto v3 expert but as ivan said you have to setup a popup manually based on the admin_id.

You could get the popup position using the [SQL API](https://carto.com/developers/sql-api/)  to get the [centroid](https://postgis.net/docs/ST_Centroid.html) of the country.


I paste a fake example, you only need to implement the `getCenter` function.


```html
<!DOCTYPE html>
<html>

<head>

  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <link rel="shortcut icon" href="http://cartodb.com/assets/favicon.ico" />
  <style>
    html,
    body,
    #map {
      height: 100%;
      padding: 0;
      margin: 0;
    }

    .buttons {
      height: 50px;
      width: 100px;
      background: rgba(0, 255, 255, 0.8);
      position: absolute;
      top: 20px;
      right: 20px;
      padding: 5px;
      border: 1px solid #FFF;
      border-radius: 5px;
      cursor: pointer;
    }
  </style>

  <link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/3.15/themes/css/cartodb.css" />
  <!--[if lte IE 8]>
        <link rel="stylesheet" href="http://libs.cartocdn.com/cartodb.js/v3/themes/css/cartodb.ie.css" />
    <![endif]-->

</head>

<body>
  <div id="map"></div>
  <div id="layer0" class="buttons" data="0">Show/hide Europe</div>
  <div id="layer1" class="buttons" data="1" style="top: 102px; background: rgba(0,255,0,0.8);">Show/hide World</div>
  <div id="layer1" class="buttons" data="2" style="top: 160px; background: rgba(255,0,0,0.8);">Show/hide China</div>




  <!-- include cartodb.js library -->
  <script src="http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js"></script>
  <script>
    function main() {

      // create leaflet map
      var map = L.map('map', {
        zoomControl: false,
        scrollWheelZoom: false,
        center: [43, 0],
        zoomControl: true,
        zoom: 2
      })

      // add a base layer
      L.tileLayer('http://tile.stamen.com/toner/{z}/{x}/{y}.png', {
        attribution: 'Stamen'
      }).addTo(map);

      var namedLayerSource = {
        user_name: 'oboix',
        type: 'namedmap',
        named_map: {
          name: "toggle_named_maps_multilayer",
          layers: [{
              layer_name: "europe"


            },
            {
              layer_name: "world"

            },
            {
              layer_name: "world_1"

            }
          ]
        }
      }
      
      // Create a popup div 
      var popup = document.createElement('div');
      popup.style.position = 'absolute';
      popup.style.background = 'white';
      popup.style.borderRadius= '4px';
      document.body.appendChild(popup);

      // add cartodb layer with one sublayer
      cartodb.createLayer(map, namedLayerSource)
        .addTo(map)
        .done(function (layer) {

          // Enable interactions events for all sublayers
          for (var i = 0; i < layer.getSubLayerCount(); ++i) {

            layer.getSubLayer(i).on('featureOver', function (e, pos, pixel, data) {
              // Get the admin center and update the popup with the data.
              var center = getCenter(data.admin).then(center => {
                popup.innerHTML = `<h1> ${data.admin} </h1>`;
                popup.style.left = center.x + 'px';
                popup.style.top = center.y + 'px';
              });
            });

            // infowindow
            cdb.vis.Vis.addInfowindow(map, layer.getSubLayer(i), ['cartodb_id', 'name']);
            // tooltip definition with createLayer

            var testTooltip = layer.leafletMap.viz.addOverlay({
              type: 'tooltip',
              layer: layer.getSubLayer(i),
              template: '', 
              width: 0, // Make invisible the old tooltip
              position: 'bottom|right',
              fields: [{
                name: 'cartodb_id'
              }]
            });
            $('body').append(testTooltip.render().el);



          }
          console.log(layer.getSubLayerCount());
          var toggle = false;

          $(".buttons").on('click', function (e) {
            var layerNum = $(e.target).attr('data');
            toggle = layer.getSubLayer(layerNum).toggle();
            console.log("layer " + layerNum + " toggled: " + toggle);
          });
        })
        .error(function (err) {
          console.log("error: " + err);
        });


        function getCenter(admin) {
          // Get the real center of the admin here using the SQL API
          return Promise.resolve({x: 1000, y: 164 });
        }
    }

    window.onload = main;
  </script>

</body>

</html>
```


Regards

**Comment by ramiroaznar** [comment]
@AryaRDI can we close this one then?

**Comment by AryaRDI** [comment]
> @AryaRDI can we close this one then?

Hi, @ramiroaznar Yes, thank you all for providing that solution. I recommend simply we provide this option for users in the later versions.

Regards

**Comment by ramiroaznar** [comment]
^^ @ivanmalagon
