### ISSUE TITLE
CartoError: serverUrl is not a valid URL.

### ISSUE THREAD

**Issue by ohnova** [CartoDB/carto.js#2197]
I've installed Carto On-Premises on a server inside closed network. When I create new carto.Client with serverUrl which is IP-Address like 192.168.0.XX, then uncaught error come out as above title.

**Comment by ivanmalagon** [comment]
What's the exact URL you're assigning?

Protocol is needed, so you would need `http:\\192.168.0.12` at least. Try that and if it doesn't work, please write the exact code that you are using, please.

**Comment by ohnova** [comment]
```javascript
import carto from '@carto/carto.js';`

export function getCarto() {
  return new carto.Client({
    apiKey: process.env.REACT_APP_CARTO_API_KEY,
    username: process.env.REACT_APP_USERNAME,
    serverUrl: process.env.REACT_APP_CARTO_SERVER_URL
  });
}
```
.env file
```javascript
...
REACT_APP_USERNAME=carto
REACT_APP_CARTO_SERVER_URL=https://192.168.0.58/user/carto
```

The serverUrl is supposed to start with 'www' + domain name, and  I think this is better because carto on-Premises has to have SSL certification.

**Comment by IagoLast** [comment]
We have to review this because allowing IPs may lead to unexpected behaviors.

As a temporary fix, my only idea is to redirect a fake URL to your IP

**Comment by Jesus89** [comment]
@ohnova this pattern (`https://192.168.0.58/user/carto`) is only available for On-Premise users.

The general way to communicate with Maps API is with subdomains. In your case, you should configure your IP as a domain (in /etc/hosts) and then use that domain in the `serverUrl` parameter. For example:

```
# /etc/hosts
192.168.0.58  carto.lan
```

```
REACT_APP_USERNAME=carto
REACT_APP_CARTO_SERVER_URL=http://{username}.carto.lan
```
