### ISSUE TITLE
v3 security vulnerabilities

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/carto.js#2202]
V3 of carto.js uses jQuery 1.7 which is vulnerable to XSS attacks. This should be update to use v3. See the vulnerabilities here: https://snyk.io/vuln/npm:jquery

I would love to see this get fixed asap.

On another note, besides being vulnerable, it doesn't match the versions of jQuery that are used in modern apps and causes collisions due to API mismatch.

**Comment by ivanmalagon** [comment]
This conversation was handled via support.
