### ISSUE TITLE
Outdated git module

### ISSUE THREAD

**Issue by gonzaloriestra** [CartoDB/carto.js#2207]
There's a [.gitmodules](https://github.com/CartoDB/carto.js/blob/ed37be2bb40d4fb647c0941fcb8eee57df94b9ce/.gitmodules ) file in the repo pointing to the path `test/lib/phantom-jasmine`, which doesn't exist.

It seems to be outdated, so maybe it could be removed.

**Comment by VictorVelarde** [comment]
This still needs a little work, as it seems that the change was not applied to v3.

**Comment by rjimenezda** [comment]
There's an open PR to remove it from v3 right?

**Comment by gonzaloriestra** [comment]
@VictorVelarde There's a open PR for it: https://github.com/CartoDB/carto.js/pull/2225

**Comment by VictorVelarde** [comment]
Yeah, I saw your PR @gonzaloriestra thx!
