### ISSUE TITLE
How to get layers for mapbox basemap

### ISSUE THREAD

**Issue by shivalkondwar** [CartoDB/carto.js#2209]
### Context
*Please explain here below what you were doing when the issue happened*

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1.
2.
3.

### Current Result
*Please describe here below the current result you got*

### Expected result
*Please describe here below what should be the expected behaviour*

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*

### Additional info
*Please add any information of interest here below*

**Comment by ivanmalagon** [comment]
CARTO.js works with Leaflet or Google Maps, not Mapbox.
If you need to work with Mapbox GL, please visit our render library https://github.com/CartoDB/carto-vl
If not, please elaborate on your answer. That title is not enough information to know what's your particular issue.

**Comment by shivalkondwar** [comment]
Thank you ivanmalagon for the response. I would like to know whether I can use CARTO.js v4 with Mapbox. As CARTO partnered with MAPBOX [link](https://carto.com/blog/partnering-with-mapbox/) in last January.

Is CARTO-VL is the only option to work with Mapbox?

**Comment by ivanmalagon** [comment]
CARTO.js is a raster library. If you need to use Mapbox GL with Carto, CARTO VL is the way to go.

**Comment by shivalkondwar** [comment]
Thanks ivanmalagon

**Comment by ivanmalagon** [comment]
CARTO.js is our raster library and it works out-of-the-box with Leaflet and Google Maps.

CARTO VL is our vector library and it works with Mapbox GL.

What exactly do you need Mapbox for? Basemaps? Combining data from CARTO with your own data...?

**Comment by shivalkondwar** [comment]
I have a requirement to convert Project-A to Project-B
1) Project-A uses google map as Basemap on client side and loads layers Json data from CartoDB. 
2) Project-B uses Mapbox as Basemap on client side and loads same data to draw layers.

So my question is can I use same data to draw layers on Mapbox?

**Comment by ivanmalagon** [comment]
How are you loading the json data? Via API? Via CARTO.js? Using directly JSON files?

**Comment by shivalkondwar** [comment]
I am loading from an API

**Comment by VictorVelarde** [comment]
Hi @shivalkondwar 
If you are going to work with CARTO VL you should have a look at its guides and examples at https://carto.com/developers/carto-vl/.

For example, you could adapt easily your API request into a GeoJSON source (simple external GeoJSON: https://carto.com/developers/carto-vl/examples/#example-external-geojson-layer).

**Comment by VictorVelarde** [comment]
I'm closing this. Feel free to open an issue at CARTO VL repository if you have any problem with your projects
