### ISSUE TITLE
Make search box use new TomTom geocoder by default

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/carto.js#2213]
### Context
As per https://github.com/CartoDB/support/issues/1885 we're going to change our default geocoder for the search bar.

This includes several steps:

### Steps

- [x] carto.js (v4). Replace the use of `carto.js/src/geo/geocoder/mapbox-geocoder.js` with a new **tomtom-geocoder.js**. See ongoing PR #2214 

- [x] carto.js (**v3**). Add new provider `cdb.geo.geocoder.TOMTOM` (like we did in https://github.com/CartoDB/carto.js/pull/2022) and use it at search (https://github.com/CartoDB/carto.js/blob/develop/src/geo/ui/search.js)

- [x] ensure both previous implementations receive the proper api_key (like we did in https://github.com/CartoDB/cartodb/pull/13427). 

- [x] Update cartodb (carto.js references + update submodule at cartodb (lib/assets/javascripts/cdb), like we did on https://github.com/CartoDB/cartodb/pull/13450

**Comment by elenatorro** [comment]
Working on production 🚀
