### ISSUE TITLE
Student Developer Pack - HOW TO ACTIVATE IT?

### ISSUE THREAD

**Issue by giuliowithg** [CartoDB/carto.js#2226]
### Context
Hello, 
I have activated the developer student pack (https://education.github.com/discount_requests/new) on my github account.
I registed in CARTO but my account is "professional trial" and I do not have the 2 year free software as promised.

Please help!
GDF

**Comment by ztephm** [comment]
CARTO Support can help adjust your plan @giuliowithg - please send an email to support@carto.com about this, including your CARTO account's username.

**Comment by VictorVelarde** [comment]
I hope you have already solved your problem, so closing this
