### ISSUE TITLE
Layers created with `createLayer` can't be added using `map.addLayer()`

### ISSUE THREAD

**Issue by acanimal** [CartoDB/carto.js#772]
It seems layers created with `createLayers` can only be added using the `addTo(map)` but fails using the other Leaflet way `map.addLayer(layer)`. As example, next code fails:

``` javascript
      var map, tileLayer, cartoLayer;

      function main() {
        map = L.map('map').setView([40, -2], 6);

        tileLayer = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png',
            {"attribution": "OSM attribution"});
        // tileLayer.addTo(map);
        map.addLayer(tileLayer);

        cartoLayer = cartodb.createLayer(map, 'https://asantiago.cartodb.com/api/v2/viz/ed191c60-7be7-11e5-b1c3-0e674067d321/viz.json');
        // cartoLayer.addTo(map);
        map.addLayer(cartoLayer);
      }
```

The error is `Uncaught TypeError: layer.onAdd is not a function`. **This is because `createlayer` returns a `_Promise` objected instead a real Leaflet of GMap layer.**

The way to do it is listening for the `done` event: 

``` javascript
createLayer(....).on('done', function(layer) {
  map.add(layer);
});
```

but it is really weird we can add a layer in a Leaflet way using the `addTo(map)` and not using the `map.addLayer()`.

**Comment by knownasilya** [comment]
Also ran into this error..
